---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: status-tacos-apple-signin-secret
  namespace: default
spec:
  encryptedData:
    private-key: AgCLlrI9nxHDgM3GqNA4Wj/yaMta7sPl8Fqa6J8M5jxyfD+X713jzo+m0dMZfjoXB6O+jkjqengKVLOLzVbbEoCQ8n8q2UMnFMXdN6dJpvTPqIduYXugjjk4PhFFGcXgxPAoo17rQFms1vkX9EAugyxI5ExzIpc1fQmr7GL2QeKTAmaRtN/ZN6/qiJAcfIS+gd2iRl+9uy8pZYsxUovUHWSG8SA3vhza9Gj2TUEGUz96hclp+Nn0m9C59DUawYUvs1x8pZtxh4ZjrNOPRkV4jkSJVuyZuuG+b1byy+z7GRtf5zz9V/Qq9s0hRpaxiyKVZ4KNCEBbRgyK6bRvTOvpE8ugrQNwdlCTPYYsHRUt6dBRJPGPjMWsTjZXrATHDd7NEcl6W+Uo7VVRk5tWF144z/VSrcPuARZuyjWqsoXMmUCFH0jlct7rXaky8it7NmJtwdQFpkd7MLt1b68KnplThL9vjTrXOtNibcX5HCPm8KfDO1FMJ9Zsp61orxd0+9+7s10iHHvMK/0LdKm8MITRGrarz5OfsIwXIX3Cg+fVN50TBivX4SfeyOTorqxwBWMfppFwA6/HLbHz5qT5w7y9GU5G6ZlqaF1nadCiVbUaMKknUQTXUt27Npty6FmhFlSMgFCkKrbMP+5f9nIItT5cWv0rlDM1QaafXfAOcbvYuISHn8YnK/3VI5USgC94YP/0plkRNKXXzOkQl9kiDe3qy2QggVOrrVhjIgR3lvHBOYuIkGVw54vIrgyUUHcrMp2tFlihw6h0NSXvhf1CQqLe+FZKOwjnz1rDu/YPqI9IkZr38xljDWzCANJ/oP+oHrBTBtUlv5lcYV3In9/lC/QJzm/HlN/fiWUU5sZCIeEdG5XC/fBSh7+pWdlWaswp4A9aKkWygDxwqyeEoL8jwqfenY+yPyW8zhFMrGlgrK2K4garm3DPPeettdvj8tq+9ojo81iovL1p9P2/K4aFA2VEKGTVf1GStB2bq40JPE9XTzlnNCMNIPeMJKYdB9MXDoeYxQidXXpFw1qa8Iby3KiQ9vDJgA==
  template:
    metadata:
      name: status-tacos-apple-signin-secret
      namespace: default
