---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: status-tacos-keycloak-admin-secret
  namespace: default
spec:
  encryptedData:
    client-secret: AgCHLPuH0tMqurF44GB1igsgoEbFbxDaOJGHN7ndfnUKb3gTn6oR6TxcrZwiAOSTVjOwTSRaFQjY66XtES2nrDeuaYcHTuV1IRdASrlvnwsZr0v79lAL0FXwFP39lBnctzNFR51C2EIPkzMV69+hnLk3eJTt/DJ7wyf6QbX+PV2IuAtRBfpwqYYRYuBu8KoEjXMtxTAWYelF4m3mibR4IIP8uFUuWI/6SlRZGmvPAp/1NhazOnibt54p4lF1K2kUxgsC3W5uuCTFOz201rhPMkA/+xQSeuYXNdgrrL6DjV/hq9sj3SMgMU7hpLv/JujolR5iH7Mb7XIpdeMJatGv5WKxSyxfZfUTv0cgRK4lN96w76uXHYypC9EA+CAuEntknRGZscHfIPv2SsHnTA9R+QuUDyl9/jWQBO7m3qZUaxXlwN5wrLogwhQ44XEQeprzLhSENFL/Jh04xDuesH635BSndUP2aMmXWvVDEFmTAL/dJstSP+Z4RLc+wR3oOwBzs/9dpXPTbhqorIcL93hurhMdRKycsWRMmJeLqUeVB0BxvpryYdrmW4GSw1lpDB09CKtZLmhkTeTXQ6LmJT8ndIknKLLMLcROn4Ak2aqhkGIXOhGbJ5k06iz0k0tPceMUJSzK4DAh78jRH44vLyCixIvhFzykBoornsq+D0Ea3/OUwkZlbVWfibF56f2mQ8jlrRz+1J7LAGUfrD6SOjLfU4ssKNN2ns74zluhAAwZWchWIg==
  template:
    metadata:
      name: status-tacos-keycloak-admin-secret
      namespace: default
