---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: status-tacos-apns-secret
  namespace: default
spec:
  encryptedData:
    private-key: AgCBhyQfMkyzz/84Aiu/GOvUXSjorZGYpz7VfhhU+3xg/lJ/r+VmwCCfesdp8hxq7BsAKpgI0o9CDfn815XjoPcS6boZFU1/EsnlS5awuGBOITeZmcHgKsRK4TF1lQpWlZ+Xsvg/XFBwtwtW5nAXzmm8ZS9GMCEVexJ95kfjN1YIaWVea2HcemTkmS6LQmG04ib83dBFagTItq+WnKl4LJggREEkYfVlhXaqRXsgS6uhA5ctk3RQHZuPR1QakJEF3uVFQNMtEIWPrKk3JB+qnj0wa9aA7OkqsiURzn6fM4wCgMg24fYWQ8VnjYxPem4ZHELTHWdmG4srZcD2e3RAuCjhkbzktlUcnCAhBJxdYrBcv4q6MAswRJzeeTDo/Kd3ptaJcbK3Gr6WAbcjRftG7BFfNFDhFEi+g7teRowDaskJ4FQ9MiLVSKV2i2FMv4S58awjt3gF9v7QGwTij+tDZOEq7/kqVrat2G0H6eXAXggyUEToJfDwDnrD/MRykqALva688pnJCzceLK50jtJV2nV5B+RQ6WeiBzp8YtZUVOgU74hOoN2xyVm0hKMsWZ+hjq2uR7uMaBWKhLTzXHwAhkW2X3PCstDvmHSkY6V/2gqSu2qiiWkoJKCVwv2kBzZum6hB3heyAWINfoeGUTLVtG0cBYHWJF02v3S4H9j2LJJW0N2n9UuFLIG7Y9OD8M0FkgZFI6SjK1tr3FI7otTXCYlZUXItQOpYw6qchrmB9RFfdibKjQKc3FxWX+mUIKYYKpNDsd5MoiZ0zofcqXJeF6a9pwZNOlrizm6Py1YYRLFFhntvd4YTYccZzXr/ODNRPkKMQnrtkSIJ8uDdflUiErBzNxn6tZ4Mph8S0mBQXG8Jy8g9yK5fweT5X0NSXmBw3R4T4ahjnxaBKZahritwUmjQHOLs6ef3azy2dQhOXOIIHoK1iHLnjwQob447yqjEpEV8kLaxwnxBD1Xyr3P2Sa0xE8a2TG5vn21X7e8nPoJuethgp6bFPXkoE99II2TrNZzxir5IFQScm+XSgOXZycl1yg==
  template:
    metadata:
      name: status-tacos-apns-secret
      namespace: default
